=== istvansalamon/XMLTaskFA6VDV/xdmschema_FA6vdv.xsd
<?xml version="1.0" encodin="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

	<!-- Felepites -->
	<xs:element name="onlinevasarlas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded"/>
                <xs:element name="felhasznalo" type="felhasznaloTipus" maxOccurs="unbounded"/>
                <xs:element name="profil" type="profilTipus" maxOccurs="unbounded"/>
                <xs:element name="fizetes" type="fizetesTipus" maxOccurs="unbounded"/>
                <xs:element name="termek" type="termekTipus" maxOccurs="unbounded"/>
                <xs:element name="vasarlas" type="vasarlasTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    
    
    <!-- elsodleges kulcsok -->
    <xs:key name="rendeles_kulcs">
        <xs:selector xpath="rendeles" />
        <xs:field xpath="@rendelesid" />
    </xs:key>

    <xs:key name="felhasznalo_kulcs">
        <xs:selector xpath="felhasznalo" />
        <xs:field xpath="@felhasznaloid" />
    </xs:key>

    <xs:key name="profil_kulcs">
        <xs:selector xpath="profil" />
        <xs:field xpath="@profilid" />
    </xs:key>

    <xs:key name="fizetes_kulcs">
        <xs:selector xpath="fizetes" />
        <xs:field xpath="@fizetesid" />
    </xs:key>

    <xs:key name="termek_kulcs">
        <xs:selector xpath="termek" />
        <xs:field xpath="@termekid" />
    </xs:key>


    <!-- idegen kulcsok -->

     <xs:keyref refer="rendeles_kulcs" name="rendeles_idegen_kulcs">
        <xs:selector xpath="vasarlas" />
        <xs:field xpath="@R-V_K" />
    </xs:keyref>

    <xs:keyref refer="termek_kulcs" name="termek_idegen_kulcs">
        <xs:selector xpath="vasarlas" />
        <xs:field xpath="@T-V_K" />
    </xs:keyref>


    <!-- 1 : 1 kapcsolatok -->
    <xs:unique name="unique_profil">
        <xs:selector xpath="profil" />
        <xs:field xpath="@profilid" />
    </xs:unique>

</xs:element>

<!-- ComplexType Tipusok -->

<xs:complexType name="rendelesTipus">
            <xs:sequence>
                <xs:element name="rendeles_datuma" type="xs:date" />
                <xs:element name="szallitasi_cim" type="cimTipus" />
                <xs:element name="osszeg" type="xs:integer" />
            </xs:sequence>
            <xs:attribute name="rendelesID" type="xs:string"  use="required" />
            <!-- idegen kucsl kell -->
</xs:complexType>

<xs:complexType name="cimTipus">
            <xs:sequence>
                <xs:element name="irsz" type="xs:integer" />
                <xs:element name="varos" type="xs:string" />
                <xs:element name="utca" type="xs:string" />
                <xs:element name="hsz" type="xs:integer" />
            </xs:sequence>
</xs:complexType>

<xs:complexType name="felhasznaloTipus">
            <xs:sequence>
                <xs:element name="felhasznalonev" type="xs:string" />
                <xs:element name="email" type="xs:string" />
                <xs:element name="regisztracio_datuma" type="xs:date" />
            </xs:sequence>
            <xs:attribute name="felhasznaloID" type="xs:string"  use="required" />
</xs:complexType>

<xs:complexType name="ProfilTipus">
            <xs:sequence>
                <xs:element name="nev" type="xs:string" />
                <xs:element name="telefonszam" type="xs:string" />
                <xs:element name="utolso_belepes_datuma" type="xs:date" />
            </xs:sequence>
            <xs:attribute name="felhasznaloID" type="xs:string"  use="required" />
</xs:complexType>

<xs:complexType name="fizetesTipus">
            <xs:sequence>
                <xs:element name="osszeg" type="xs:integer" />
                <xs:element name="tranzakcio_datuma" type="xs:date" />
                <xs:element name="fizetesimod" type="xs:string" />
                
            </xs:sequence>
            <xs:attribute name="tranzakcioID" type="xs:string"  use="required" />
</xs:complexType>

<xs:complexType name="termekTipus">
            <xs:sequence>
                <xs:element name="termeknev" type="xs:string" />
                <xs:element name="ar" type="xs:integer" />
                <xs:element name="keszlet" type="xs:integer" />
            </xs:sequence>
            <xs:attribute name="termekID" type="xs:string"  use="required" />
            <!-- idegen kucsl -->

</xs:complexType>

</xs:schema>

=== istvansalamon/XMLTaskFA6VDV/DOMParseFA6VDV/src/hu/domparse/fa6vdv/XMLFA6VDV.xml
<?xml version="1.0" encoding="UTF-8"?>

<onlinevasarlas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="xdmschema_FA6vdv.xsd">

    <rendeles rendelesid="R1" R-V_K="RVK1">
        <rendeles_datuma>2023-01-01</rendeles_datuma>
        <szallitasi_cim>
            <irsz>1328</irsz>
            <varos>Budapest</varos>
            <utca>Kossuth utca</utca>
            <hsz>12</hsz>
        </szallitasi_cim>
        <osszeg>14990</osszeg>

    </rendeles>

    <rendeles rendelesid="R2" R-V_K="RVK2">
        <rendeles_datuma>2023-01-01</rendeles_datuma>
        <szallitasi_cim>
            <irsz>3300</irsz>
            <varos>Eger</varos>
            <utca>Dobó </utca>
            <hsz>56</hsz>
        </szallitasi_cim>
        <osszeg>8990</osszeg>
    </rendeles>


    <felhasznalo felhasznaloid="F1">
        <felhasznalonev>szabi</felhasznalonev>
        <email>szabi.lantos@freemail.com</email>
        <regisztracio_datuma>2022-12-02</regisztracio_datuma>
    </felhasznalo>

    <felhasznalo felhasznaloid="F2">
        <felhasznalonev>evike</felhasznalonev>
        <email>evike@citromail.com</email>
        <regisztracio_datuma>2016-04-15</regisztracio_datuma>
    </felhasznalo>

    <profil profilid="E1">
        <nev>Lantos Szabolcs</nev>
        <telefonszam>+36205555444</telefonszam>
        <utolso_belepes_datuma>2023-10-02</utolso_belepes_datuma>
    </profil>

    <profil profilid="E2">
        <nev>Nagy Éva</nev>
        <telefonszam>+36209453264</telefonszam>
        <utolso_belepes_datuma>2023-09-30</utolso_belepes_datuma>
    </profil>

    <fizetes fizetesid="T1">
        <osszeg>14990</osszeg>
        <tranzakcio_datuma>2023-10-02</tranzakcio_datuma>
        <fizetesimod>Kártya</fizetesimod>
    </fizetes>

    <fizetes fizetesid="T2">
        <osszeg>8990</osszeg>
        <tranzakcio_datuma>2023-09-30</tranzakcio_datuma>
        <fizetesimod>Kártya</fizetesimod>
    </fizetes>

    <termek termekid="P1" T-V_K="TVK1">
        <termeknev>Egér</termeknev>
        <ar>4990</ar>
        <keszlet>10</keszlet>
    </termek>

    <termek termekid="P2" T-V_K="TVK2">
        <termeknev>Billentyűzet</termeknev>
        <ar>12000</ar>
        <keszlet>25</keszlet>
    </termek>

    <termek termekid="P3" T-V_K="TVK3">
        <termeknev>ssd 256</termeknev>
        <ar>8990</ar>
        <keszlet>5</keszlet>
    </termek>

    <termek termekid="P4" T-V_K="TVK4">
        <termeknev>usb kábel</termeknev>
        <ar>500</ar>
        <keszlet>8</keszlet>
    </termek>


    <vasarlas >
        <szemelyes>0</szemelyes>
        <online>2</online>
    </vasarlas>

</onlinevasarlas>

=== istvansalamon/XMLTaskFA6VDV/DOMParseFA6VDV/out/production/DOMParseFA6VDV/hu/domparse/fa6vdv/XMLFA6VDV_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<onlinevasarlas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xdmschema_FA6vdv.xsd">
  <rendeles R-V_K="RVK1" rendelesid="R1">
    <rendeles_datuma>2023-01-01</rendeles_datuma>
    <szallitasi_cim>
      <irsz>1328</irsz>
      <varos>Budapest</varos>
      <utca>Kossuth utca</utca>
      <hsz>12</hsz>
    </szallitasi_cim>
    <osszeg>14990</osszeg>
  </rendeles>
  <rendeles R-V_K="RVK2" rendelesid="R2">
    <rendeles_datuma>2023-01-01</rendeles_datuma>
    <szallitasi_cim>
      <irsz>3300</irsz>
      <varos>Eger</varos>
      <utca>Dob√≥</utca>
      <hsz>56</hsz>
    </szallitasi_cim>
    <osszeg>8990</osszeg>
  </rendeles>
  <felhasznalo felhasznaloid="F1">
    <felhasznalonev>szabi</felhasznalonev>
    <email>szabi.lantos@freemail.com</email>
    <regisztracio_datuma>2022-12-02</regisztracio_datuma>
  </felhasznalo>
  <felhasznalo felhasznaloid="F2">
    <felhasznalonev>evike</felhasznalonev>
    <email>evike@citromail.com</email>
    <regisztracio_datuma>2016-04-15</regisztracio_datuma>
  </felhasznalo>
  <profil profilid="P1">
    <nev>John Doe</nev>
    <telefonszam>06204455788</telefonszam>
    <utolso_belepes_datuma>2023-04-22</utolso_belepes_datuma>
  </profil>
  <profil profilid="P2">
    <nev>Jane Doe</nev>
    <telefonszam>06301455789</telefonszam>
    <utolso_belepes_datuma>2023-02-01</utolso_belepes_datuma>
  </profil>
  <termek T-V_K="TVK1" termekid="T1">
    <termeknev>Laptop</termeknev>
    <ar>250000</ar>
    <keszlet>20</keszlet>
  </termek>
  <termek T-V_K="TVK2" termekid="T2">
    <termeknev>Mobil telefon</termeknev>
    <ar>80000</ar>
    <keszlet>50</keszlet>
  </termek>
</onlinevasarlas>
